### ISSUE TITLE
Any update on the sharing of this beta ?

### ISSUE THREAD

**Issue by guillaume-kizilian** [sergeluca/Power-Platform-BPM-Toolkit#1]
I am eager to try this BPM Toolkit :)

Thanks.

**Comment by jachockey012** [comment]
This ^^

**Comment by sergeluca** [comment]
Hello. Yes, I'm working on the setup documentation. I did create a video for the setup the last weekend, and I've tested it with Isabelle. It was too complex. I will work on this setup tutorial tomorrow + test it again with Isabelle, and we will see. The main concern is to make the setup smooth enough for you guys :-). There are 55 flows based on SharePoint lists, and the ALM tool I've created for deploying the BPM Toolkit has been updated. So I'm creating a video and a setup document, but only during my free time

**Comment by jachockey012** [comment]
I think the complexity is the exciting part. Also the deployment tool makes it even more exciting to see. Thank you for the update! Looking forward to play with it when you two get the free time to finish it up.
