### ISSUE TITLE
Missing/incomplete Flows in BPM Toolkit - ALM solution

### ISSUE THREAD

**Issue by qtstech** [sergeluca/Power-Platform-BPM-Toolkit#2]
Hi Serge,

Thanks very much for nice toolkit.  I tried to install solutions but I see that some Flows are missing and some are incomplete in the BPM Toolkit - ALM solution.  

Thanks again

**Comment by sergeluca** [comment]
I apologize for this. Indeed there is something wrong with this package. I will double-check everything again, and I will upload a new zip.

**Comment by sergeluca** [comment]
ok I've uploaded the new packages. And I've updated the setup guide as well. Sorry for this

**Comment by qtstech** [comment]
Thanks very much for quickly fixing and uploaded it.  I was able to complete the initial setup.  Nice work!!
