### ISSUE TITLE
Error with the BPM Toolkit - ALM - Search and Replace

### ISSUE THREAD

**Issue by FrankLeTank88** [sergeluca/Power-Platform-BPM-Toolkit#3]
Hi Ive tried installing the solution on a demo tenant as suggested, I have an issue with the BPM Tool kit - ALM Search and Replace when i run the flow it says succeeded but when I check the run history under the "Main"  Action under the "Apply To Each" function i have one failed the last one 73/73 update record ? 
WorkflowOperationParametersRuntimeMissingValue. The 'inputs.parameters' of workflow operation 'Update_a_record' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

**Comment by sergeluca** [comment]
Hello,

can you try again with "Pass1" ?

Kind regards


Serge Luca

Office Applications and Services (Office 365) MVP

Business Applications (Power Automate & PowerApps) MVP

Power Platform Associates, Belgium

P: +32 472 885 928

E: sergeluca@powerplatformassociates.com<mailto:sergeluca@powerplatformassociates.com>

Blog<http://sergeluca.wordpress.com/> | Linkedin <http://www.linkedin.com/in/sergeluca> | Twitter <http://www.twitter.com/sergeluca> | Web<http://www.shareql.com/>


[cid:fc185a79-df77-4ab4-a61a-ad1e25ccf6f2]


[cid:8a2b8ca6-16d1-4501-b933-32c62777345e]

________________________________

**Comment by sergeluca** [comment]
If this does not work, we can organize a Teams meeting/screen sharing

**Comment by FrankLeTank88** [comment]
Hi Serge,

Thank you for the quick response,

I tried running the "Pass1" 4 times but kept getting the same error on the last update record.

I then carried on the process and im near completion once complete ill test it and if I have any issues can we set up a quick teams or screen share please?

You have built an amazing solution thank you!!

 Kind Regards

Frank Ross

**Comment by sergeluca** [comment]
Hi Frank,

If it fails at step 73, it is the update of the flow:
 {
    "name": "BPM Toolkit - Workflow Runtime - Compute final Workflow Status"
  }


The consequence of this is that when the approval process completes, it won’t be able to define the outcome of the process (approved or rejected).
You can keep working on the process and yes we can organize a team meeting. Pass 2 was ok ?
I won’t let you down 😊

Serge

**Comment by FrankLeTank88** [comment]
Hi Serge,

Thank you for the quick response, i really appreciate all your help and effort.

Once I have completed the process and check if it is running I will ask you to arrange a Teams meeting,

What would be the best way to contact you to organize the meeting?

Thank you once again!

**Comment by sergeluca** [comment]
What is your time zone?
For the Team meeting, my e-mail is sergeluca@shareql.com




Serge Luca

Office Applications and Services (Office 365) MVP

Business Applications (Power Automate & PowerApps) MVP

Power Platform Associates, Belgium

P: +32 472 885 928

E: sergeluca@powerplatformassociates.com<mailto:sergeluca@powerplatformassociates.com>

Blog<http://sergeluca.wordpress.com/> | Linkedin <http://www.linkedin.com/in/sergeluca> | Twitter <http://www.twitter.com/sergeluca> | Web<http://www.shareql.com/>


[cid:3c96a0e0-3c6e-4d4f-beeb-3f7656e17c5b]


[cid:10eb8e84-2df4-4c4a-b20c-79877246d54e]

________________________________

**Comment by FrankLeTank88** [comment]
Hi Serge,

I am GMT +2 and yours?

I found another issue I am on the PPA order form and I dont have "PPA-SubmitDataToBPMToolkit" Flow

Im so sorry for bugging you on this but I am learning a lot from your solution and videos.

My email is fross@cfaomotorssa.co.za

**Comment by sergeluca** [comment]
I’m in GMT+1 (Brussels), so it will be easy.
Regarding PPA_submitDataToBPMToolkit, the reason is you have a new version of the BPM Toolkit  and I made this flow more generic.
IT is now in the BPM Toolkit solution and the name is BPMToolkit-SubmitFormdata-Proxy (and BPMToolkit-SubmitFormdata)
I haven’t updated the video yet, but it is mentioned in the setup guide point 25 (sorry, I have to re-create a new video, or add a caption)

[cid:image001.png@01D70518.EE6C54F0]

**Comment by FrankLeTank88** [comment]
Hi Serge,

ok awesome thank you I appreciate the help, I am almost complete with the install so hopefully we can set up some time soon.

Thank you once again!

**Comment by FrankLeTank88** [comment]
Hi Serge,

Thank you for all your help and assistance I really appreciate all your effort and help.

Thank you once again Dr Flow
