### ISSUE TITLE
missing flow(s)?

### ISSUE THREAD

**Issue by jbo-matchyourit** [sergeluca/Power-Platform-BPM-Toolkit#6]
Hi Serge

I tried setup_02_07_2021_v2.zip

The ALM search and replace flow fails at step #73 in apply to each
The list records" action has as input
name eq 'BPM Toolkit - Set Final Workflow Status'
There seems not to be such flow - has it been removed?

Also there are no flows left in the demo package - on purpose?

BR
Jesper Bo Olesen

**Comment by sergeluca** [comment]
Hello Jesper, I'm on the go so I have not my laptop here, but I think that indeed this flow is not needed anymore. Sorry about this. I have to update the setup doc with this info...
Serge

**Comment by jbo-matchyourit** [comment]
Hi Serge
Thanks for a super fast answer
I'll continue then and see what happens :-)

Jesper

**Comment by sergeluca** [comment]
Jesper, don't hesitate to drop me an e-mail and if needed we can have a team meeting. The product is still in preview, production in April. Serge

**Comment by jbo-matchyourit** [comment]
Thanks
I know you stressed it's trial. I tried a version early january without success
Due to no time available I had to wait. But now ...

Jesper

**Comment by sergeluca** [comment]
ok, the setup is complex, but due to new changes in the platform, it will become easier in the coming weeks. If you want we can have a team meeting tomorrow afternoon ->this time it should work :-) . Just send me your e-mail to sergeluca@shareql.com if you want
