### ISSUE TITLE
Missing Flow in BPM Toolkit demo solution

### ISSUE THREAD

**Issue by tchinnin** [sergeluca/Power-Platform-BPM-Toolkit#7]
Hi Serge,
Trying to import the Demo solution following your Youtube video. 
I think there is a missing flow in the 10.0.0.25 version : I can't find the PPA-SubmitDataToBPMToolkit flow

![image](https://user-images.githubusercontent.com/46782173/115006553-4dfcb200-9ea9-11eb-8f81-b1ab8b87aaa5.png)

**Comment by sergeluca** [comment]
Hello Theo, I apologize. This flow is still in the list of flows, but we don't need it anymore (it was something from the previous preview). It has been made more generic and is named "BPM Toolkit SubmitFormData...." or something like this. So you can continue. Serge

**Comment by tchinnin** [comment]
Yes I just saw you explained this on the PDF, my bad
