### ISSUE TITLE
Title field in SPO lists

### ISSUE THREAD

**Issue by spooqy** [sergeluca/Power-Platform-BPM-Toolkit#9]
It's not an issue but something to consider. 
Each SPO list has Title field. That's ok for me but if I would like to invite business users to modify workflow parameters themselves, I have to hide/change the field in all configurations lists. Not everyone can understand what is the purpose of this field :)

**Comment by sergeluca** [comment]
You are right. What is planned is a PowerApps UI on top of most lists. For creating requests infos,  create/update worklows,.... thank you for the feedback!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Marcin Siewnicki ***@***.***>
Sent: Saturday, May 8, 2021 11:44:18 PM
To: sergeluca/Power-Platform-BPM-Toolkit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sergeluca/Power-Platform-BPM-Toolkit] Title field in SPO lists (#9)


It's not an issue but something to consider.
Each SPO list has Title field. That's ok for me but if I would like to invite business users to modify workflow parameters themselves, I have to hide/change the field in all configurations lists. Not everyone can understand what is the purpose of this field :)
